### ISSUE TITLE
Theoretical Framework Roadmap

### ISSUE THREAD

**Issue by simonlovesyou** [simonlovesyou/master-thesis-onboarding#18]
# Theoretical Framework
Roadmap of the Theoretical Framework which consists of `Theoretical Background` and `Best practice analysis`

### Acquisition
- [x] Needs
- [x] Motivation
- [ ] Innovation Diffusion Theory
- [ ] TAM
- [x] FBM
### Accommodation
- [ ] Behavior
- [ ] Flow
- [x] Mental models
- [ ] Gulf of evaluation and execution
- [ ] Learnability
- [ ] Feedback
- [ ] Human-Computer Dialogue
- [ ] Cognitive load
- [ ] Affordances / Signals
### Assimilation
- [ ] Community
- [ ] Design
### Acceleration
- [ ] Mental model maintenance & building

## Best practice analysis
- [ ] Choose applications with different onboarding techniques
### Dots
- [x] Take screenshots
- [ ] Analyze
- [ ] Write down the analysis
